### ISSUE TITLE
Why ground truth(gt_sel) is participate here?

### ISSUE THREAD

**Issue by guotong1988** [xxj96/SQLNet#3]
https://github.com/xxj96/SQLNet/blob/master/sqlnet/model/modules/aggregator_predict.py#L41

What if test/predict mode which don't have the ground truth?

Thank you @xxj96

**Comment by xxj96** [comment]
Hi, the ground truth of selection is used so that the attention of aggregator is conditioned on the selected column. I haven't realized the test mode which doesn't require the ground truth yet because the breakdown accuracy on aggregator requires the ground truth of selection. So even in test mode, the model will use the ground truth of selection. It will not affect the overall accuracy, but yes, I do need to realize the mode which first predicts the selected column and then uses it to predict aggregator.

**Comment by guotong1988** [comment]
Thank you
